### ISSUE TITLE
Bajo jajo bajo jajo

### ISSUE THREAD

**Issue by Jakub-Tyszkiewicz** [Osariusz/rpg-bot#2]
Nazywam się Meeseeran, od dwudziestu minut jestem właścicielem tego oto RPGa. Powoli zaczynam żałować decyzji. W nocy pustki, w dzień nadmiar lore'u. Brak startowego lore i brak firm graczy robią swoje. Zgadza się, dead chat.
Ahh skłamałem, nie posiadam tego chlewu. Prowadzę go wspólnie z Glosarem.

**Comment by MrCabbageStick** [comment]
Wałkowane tysiąc razy zamykam

**Comment by lore498** [comment]
Nie, to ja zamykam
